### ISSUE TITLE
ROS1 installation?

### ISSUE THREAD

**Issue by ziriax** [ms-iot/ros_msft_camera#14]
First of all, many thanks for sharing this code!

I was looking for a way to stream MJPEG from a Logitech 925e webcam without decoding it, even when the webcam is being used for e.g. video conferencing, and found this project. A decade ago I would use DirectShow for this, but this seems deprecated.

I tried to follow the installation instructions, but neither `roslaunch ros_msft_camera ros_msft_camera.launch` nor `catkin_make -DENABLE_RTSP=1` worked for me.

Just to make sure, if I follow the setup at http://wiki.ros.org/Installation/Windows for `noetic`, this should all just work?

**Comment by ooeygui** [comment]
Hi @Ziriax ,
Thank you for checking out this ROS node. Yes, it should just work. 
I'm looking at this now to ensure that there wasn't a regression.

**Comment by ooeygui** [comment]
Sorry about that - I renamed the ROS node and missed one of the launch files.

**Comment by ooeygui** [comment]
Sorry about the problem. Fix is checked in.
https://github.com/ms-iot/ros_msft_camera/commit/b9ccc5d2d0968cd4529a6c93d1f1e598853a2821
