### ISSUE TITLE
camera turns on but window isn't showing up

### ISSUE THREAD

**Issue by HanDaSeul** [ms-iot/ros_msft_camera#6]
Understand me just beginner of ROS and this is the first time writting a question on the github. I don't use any linux or kinda VM, just only windows 10 with melodic. I'm using a built-in camera using my laptop and when i run "rosrun win_camera win_camera-node", the LED of showing the camera status has turned on but the window isn't showing up. And this is the message i got. 
With that error, camera calibration adding --no-service-check also show me an error both no response and lag.

`**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.6.3
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************

C:\Users\HandaseulKim>rosrun win_camera win_camera_node

Setting resolution :640x480@30.000000No matching resolution and subtype supported by source. Setting up a conversion[ INFO] [1595227119.036020300]: using default calibration URL
[ INFO] [1595227119.037288900]: camera calibration URL: file:///camera_info/camera.yaml
[ INFO] [1595227119.037556800]: Unable to open camera calibration file [/camera_info/camera.yaml]
[ WARN] [1595227119.037723400]: Camera calibration file /camera_info/camera.yaml not found.`

**Comment by HanDaSeul** [comment]
> Understand me just beginner of ROS and this is the first time writting a question on the github. I don't use any linux or kinda VM, just only windows 10 with melodic. I'm using a built-in camera using my laptop and when i run "rosrun win_camera win_camera-node", the LED of showing the camera status has turned on but the window isn't showing up. And this is the message i got.
> With that error, camera calibration adding --no-service-check also show me an error both no response and lag.
> 
> `**********************************************************************
> ** Visual Studio 2019 Developer Command Prompt v16.6.3
> ** Copyright (c) 2020 Microsoft Corporation
> 
> C:\Users\HandaseulKim>rosrun win_camera win_camera_node
> 
> Setting resolution :[640x480@30.000000No](mailto:640x480@30.000000No) matching resolution and subtype supported by source. Setting up a conversion[ INFO] [1595227119.036020300]: using default calibration URL
> [ INFO] [1595227119.037288900]: camera calibration URL: file:///camera_info/camera.yaml
> [ INFO] [1595227119.037556800]: Unable to open camera calibration file [/camera_info/camera.yaml]
> [ WARN] [1595227119.037723400]: Camera calibration file /camera_info/camera.yaml not found.`

I just got a little bit of clue that it depends on the resolution, but most thing is on GUID, so i try keeping change multiple times which one is matching with and building again and again....finally i got different message, but still when i try visualizing with rqt, it's just show me half-white and black image. This message is what i got.

Setting resolution :640x480@30.000000Native res set[ INFO] [1595257674.967075200]: using default calibration URL
[ INFO] [1595257674.968521500]: camera calibration URL: file:///camera_info/camera.yaml
[ INFO] [1595257674.969109300]: Unable to open camera calibration file [/camera_info/camera.yaml]
[ WARN] [1595257674.969331100]: Camera calibration file /camera_info/camera.yaml not found.

**Comment by ooeygui** [comment]
Hello @HanDaSeul,
WinML publishes two topics - an image_raw and a marker array. you can view these in rViz. 
It's ok if you don't have a camera calibration file. That's really only needed for the 3D pose detector codepath.

**Comment by HanDaSeul** [comment]
> Hello @HanDaSeul,
> WinML publishes two topics - an image_raw and a marker array. you can view these in rViz.
> It's ok if you don't have a camera calibration file. That's really only needed for the 3D pose detector codepath.

I was wrong. I was searching on the google with Youtube and comparing with someone's ubuntu. There's no relation with calibration. I thought it's an error cause you know, as you see the message above, it's seemed to be there's an error releated to setting resolution or GUID. But, I struggled and wasted my time for the answer, and the answer is, just ignore the message. It doesn't have meaning that's not an error. My fault is, checking the path. For Windows10, when i put command 'rostopic list'  i saw the path was slightly little bit different with the ubuntu, and change the path and confirmed it works fine rqt, too. 

Now it works fine. Thanks

**Comment by HanDaSeul** [comment]
> Hello @HanDaSeul,
> WinML publishes two topics - an image_raw and a marker array. you can view these in rViz.
> It's ok if you don't have a camera calibration file. That's really only needed for the 3D pose detector codepath.

@ooeygui I have quistion

**Comment by HanDaSeul** [comment]
@ooeygui  I have question. Other guys when they run uvc_camera or kinda driver node on their ubuntu, it shows so many info like int(Brightness, 0......), int(Contrast, 0, ....)...etc. But my win_camera doens't show. Is that normal or problem on my windows?

**Comment by ooeygui** [comment]
That user interface is custom to the uvc_camera, it hasn't been ported to Windows as far as I know.

For Windows, we recommend using the new [ros_win_camera](https://github.com/ms-iot/ros_win_camera). The latter uses Windows Media Foundation. 

Here's an example of how to consume the [winml_ros node](https://github.com/ms-iot/ros_winml_arm/blob/master/k4a_arm_support/src/k4a_arm_support.cpp)

**Comment by HanDaSeul** [comment]
> That user interface is custom to the uvc_camera, it hasn't been ported to Windows as far as I know.
> 
> For Windows, we recommend using the new [ros_win_camera](https://github.com/ms-iot/ros_win_camera). The latter uses Windows Media Foundation.
> 
> Here's an example of how to consume the [winml_ros node](https://github.com/ms-iot/ros_winml_arm/blob/master/k4a_arm_support/src/k4a_arm_support.cpp)

Alright, i need to track sometimes if there's new. And can I use multiple cameras as long as I know the deviceID?
